#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

CMD=$1
[[ $CMD ]] && {
  shift
  APP=$1
  [[ $APP ]] && {
    shift
    OPTIONS_STRING="$@"
  }
}

# Check if application is specified
if [[ $CMD == ngrok ]] || [[ $CMD == ngrok:* ]]; then
  if [[ ! $APP ]]; then
    echo "You must specify an app name"
    exit 1
  else
    NGROK_OPTIONS_FILE="NGROK_OPTIONS"
    NGROK_OPTIONS_FILE_PATH="$DOKKU_ROOT/$APP/$NGROK_OPTIONS_FILE"

    # Check if app exists with the same name
    if [ ! -d "$DOKKU_ROOT/$APP" ]; then
      echo "App $APP does not exist"
      exit 1
    fi

    [ -f $NGROK_OPTIONS_FILE_PATH ] || {
      touch $NGROK_OPTIONS_FILE_PATH
    }
  fi
fi

case "$CMD" in
  # Display applications ngrok options
  ngrok)

    if [ ! -f $NGROK_OPTIONS_FILE_PATH ] || [ ! -s $NGROK_OPTIONS_FILE_PATH ] ; then
      echo "$APP has no ngrok options"
      exit 1
    fi

    cat $NGROK_OPTIONS_FILE_PATH
  ;;

  # Add a ngrok option from application
  ngrok:add)
    if [[ ! $OPTIONS_STRING ]]; then
      echo "Usage: dokku ngrok:add <app> OPTIONS_STRING"
      echo "Must specify OPTIONS_STRING to add."
      exit 1
    fi

    echo "$OPTIONS_STRING" >> $NGROK_OPTIONS_FILE_PATH
    NGROK_OPTIONS_TEMP=`cat $NGROK_OPTIONS_FILE_PATH`
    echo -e "$NGROK_OPTIONS_TEMP" | sed '/^$/d' | sort -u > $NGROK_OPTIONS_FILE_PATH
  ;;

  # Remove a ngrok option from application
  ngrok:remove)
    if [[ ! $OPTIONS_STRING ]]; then
      echo "Usage: dokku ngrok:remove <app> OPTIONS_STRING"
      echo "Must specify OPTIONS_STRING to remove."
      exit 1
    fi

    NGROK_OPTIONS_TEMP=`cat "${NGROK_OPTIONS_FILE_PATH}"`
    NGROK_OPTIONS_TEMP=$(echo -e "${NGROK_OPTIONS_TEMP}" | sed "s#${OPTIONS_STRING}##")
    echo -e "$NGROK_OPTIONS_TEMP" | sed '/^$/d' | sort -u > $NGROK_OPTIONS_FILE_PATH
  ;;

  help)
    cat && cat<<EOF
    ngrok <app>                                     Display the status of ngrok configuration on an app
    ngrok:add <app> OPTIONS_STRING                  Add an ngrok option string
    ngrok:remove <app> OPTIONS_STRING               Remove an ngrok option string
EOF
    ;;

esac
